// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: proto/cosmos/lms/v1beta1/query.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//	message Students {
//	    string address = 1;
//	    string name = 2;
//	    string id = 3;
//	}
type GetStudentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetStudentRequest) Reset() {
	*x = GetStudentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_cosmos_lms_v1beta1_query_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStudentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentRequest) ProtoMessage() {}

func (x *GetStudentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cosmos_lms_v1beta1_query_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentRequest.ProtoReflect.Descriptor instead.
func (*GetStudentRequest) Descriptor() ([]byte, []int) {
	return file_proto_cosmos_lms_v1beta1_query_proto_rawDescGZIP(), []int{0}
}

func (x *GetStudentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetStudentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Student *Student `protobuf:"bytes,1,opt,name=student,proto3" json:"student,omitempty"`
}

func (x *GetStudentResponse) Reset() {
	*x = GetStudentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_cosmos_lms_v1beta1_query_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStudentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentResponse) ProtoMessage() {}

func (x *GetStudentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cosmos_lms_v1beta1_query_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentResponse.ProtoReflect.Descriptor instead.
func (*GetStudentResponse) Descriptor() ([]byte, []int) {
	return file_proto_cosmos_lms_v1beta1_query_proto_rawDescGZIP(), []int{1}
}

func (x *GetStudentResponse) GetStudent() *Student {
	if x != nil {
		return x.Student
	}
	return nil
}

type GetStudentsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetStudentsRequest) Reset() {
	*x = GetStudentsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_cosmos_lms_v1beta1_query_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStudentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentsRequest) ProtoMessage() {}

func (x *GetStudentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cosmos_lms_v1beta1_query_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentsRequest.ProtoReflect.Descriptor instead.
func (*GetStudentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_cosmos_lms_v1beta1_query_proto_rawDescGZIP(), []int{2}
}

type GetStudentsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Students []*Student `protobuf:"bytes,1,rep,name=students,proto3" json:"students,omitempty"`
}

func (x *GetStudentsResponse) Reset() {
	*x = GetStudentsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_cosmos_lms_v1beta1_query_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStudentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentsResponse) ProtoMessage() {}

func (x *GetStudentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cosmos_lms_v1beta1_query_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentsResponse.ProtoReflect.Descriptor instead.
func (*GetStudentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_cosmos_lms_v1beta1_query_proto_rawDescGZIP(), []int{3}
}

func (x *GetStudentsResponse) GetStudents() []*Student {
	if x != nil {
		return x.Students
	}
	return nil
}

type GetLeaveRequestsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetLeaveRequestsRequest) Reset() {
	*x = GetLeaveRequestsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_cosmos_lms_v1beta1_query_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLeaveRequestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaveRequestsRequest) ProtoMessage() {}

func (x *GetLeaveRequestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cosmos_lms_v1beta1_query_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaveRequestsRequest.ProtoReflect.Descriptor instead.
func (*GetLeaveRequestsRequest) Descriptor() ([]byte, []int) {
	return file_proto_cosmos_lms_v1beta1_query_proto_rawDescGZIP(), []int{4}
}

type GetLeaveRequestsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Leaverequest []*ApplyLeaveRequest `protobuf:"bytes,1,rep,name=leaverequest,proto3" json:"leaverequest,omitempty"`
}

func (x *GetLeaveRequestsResponse) Reset() {
	*x = GetLeaveRequestsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_cosmos_lms_v1beta1_query_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLeaveRequestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaveRequestsResponse) ProtoMessage() {}

func (x *GetLeaveRequestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cosmos_lms_v1beta1_query_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaveRequestsResponse.ProtoReflect.Descriptor instead.
func (*GetLeaveRequestsResponse) Descriptor() ([]byte, []int) {
	return file_proto_cosmos_lms_v1beta1_query_proto_rawDescGZIP(), []int{5}
}

func (x *GetLeaveRequestsResponse) GetLeaverequest() []*ApplyLeaveRequest {
	if x != nil {
		return x.Leaverequest
	}
	return nil
}

type GetLeaveApprovesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetLeaveApprovesRequest) Reset() {
	*x = GetLeaveApprovesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_cosmos_lms_v1beta1_query_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLeaveApprovesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaveApprovesRequest) ProtoMessage() {}

func (x *GetLeaveApprovesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cosmos_lms_v1beta1_query_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaveApprovesRequest.ProtoReflect.Descriptor instead.
func (*GetLeaveApprovesRequest) Descriptor() ([]byte, []int) {
	return file_proto_cosmos_lms_v1beta1_query_proto_rawDescGZIP(), []int{6}
}

type GetLeaveApprovesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Leaveapprove []*AcceptLeaveRequest `protobuf:"bytes,1,rep,name=leaveapprove,proto3" json:"leaveapprove,omitempty"`
}

func (x *GetLeaveApprovesResponse) Reset() {
	*x = GetLeaveApprovesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_cosmos_lms_v1beta1_query_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLeaveApprovesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaveApprovesResponse) ProtoMessage() {}

func (x *GetLeaveApprovesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cosmos_lms_v1beta1_query_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaveApprovesResponse.ProtoReflect.Descriptor instead.
func (*GetLeaveApprovesResponse) Descriptor() ([]byte, []int) {
	return file_proto_cosmos_lms_v1beta1_query_proto_rawDescGZIP(), []int{7}
}

func (x *GetLeaveApprovesResponse) GetLeaveapprove() []*AcceptLeaveRequest {
	if x != nil {
		return x.Leaveapprove
	}
	return nil
}

var File_proto_cosmos_lms_v1beta1_query_proto protoreflect.FileDescriptor

var file_proto_cosmos_lms_v1beta1_query_proto_rawDesc = []byte{
	0x0a, 0x24, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2f, 0x6c,
	0x6d, 0x73, 0x2f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2f, 0x71, 0x75, 0x65, 0x72, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x6c, 0x6d, 0x73, 0x2e, 0x76, 0x31, 0x62, 0x65,
	0x74, 0x61, 0x31, 0x1a, 0x21, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x73, 0x6d, 0x6f,
	0x73, 0x2f, 0x6c, 0x6d, 0x73, 0x2f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2f, 0x74, 0x78,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x23, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x53, 0x74, 0x75,
	0x64, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x44, 0x0a, 0x12, 0x47,
	0x65, 0x74, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2e, 0x0a, 0x07, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6c, 0x6d, 0x73, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31,
	0x2e, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x52, 0x07, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e,
	0x74, 0x22, 0x14, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x47, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x53, 0x74,
	0x75, 0x64, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30,
	0x0a, 0x08, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x6c, 0x6d, 0x73, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x53,
	0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x52, 0x08, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x73,
	0x22, 0x19, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x5e, 0x0a, 0x18, 0x47,
	0x65, 0x74, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x0c, 0x6c, 0x65, 0x61, 0x76, 0x65,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e,
	0x6c, 0x6d, 0x73, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x41, 0x70, 0x70, 0x6c,
	0x79, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0c, 0x6c,
	0x65, 0x61, 0x76, 0x65, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x19, 0x0a, 0x17, 0x47,
	0x65, 0x74, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x5f, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x4c, 0x65, 0x61,
	0x76, 0x65, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x43, 0x0a, 0x0c, 0x6c, 0x65, 0x61, 0x76, 0x65, 0x61, 0x70, 0x70, 0x72, 0x6f,
	0x76, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6c, 0x6d, 0x73, 0x2e, 0x76,
	0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x4c, 0x65, 0x61,
	0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0c, 0x6c, 0x65, 0x61, 0x76, 0x65,
	0x61, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x32, 0xf2, 0x02, 0x0a, 0x05, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x12, 0x52, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x73,
	0x12, 0x1f, 0x2e, 0x6c, 0x6d, 0x73, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x47,
	0x65, 0x74, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x20, 0x2e, 0x6c, 0x6d, 0x73, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4f, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x53, 0x74, 0x75, 0x64,
	0x65, 0x6e, 0x74, 0x12, 0x1e, 0x2e, 0x6c, 0x6d, 0x73, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61,
	0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x6c, 0x6d, 0x73, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61,
	0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x61, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x4c, 0x65, 0x61,
	0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x12, 0x24, 0x2e, 0x6c, 0x6d, 0x73,
	0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x65, 0x61, 0x76,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x25, 0x2e, 0x6c, 0x6d, 0x73, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x47,
	0x65, 0x74, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x61, 0x0a, 0x10, 0x47, 0x65, 0x74,
	0x4c, 0x65, 0x61, 0x76, 0x65, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x73, 0x12, 0x24, 0x2e,
	0x6c, 0x6d, 0x73, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4c,
	0x65, 0x61, 0x76, 0x65, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x6c, 0x6d, 0x73, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61,
	0x31, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76,
	0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0d, 0x5a, 0x0b,
	0x78, 0x2f, 0x6c, 0x6d, 0x73, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_cosmos_lms_v1beta1_query_proto_rawDescOnce sync.Once
	file_proto_cosmos_lms_v1beta1_query_proto_rawDescData = file_proto_cosmos_lms_v1beta1_query_proto_rawDesc
)

func file_proto_cosmos_lms_v1beta1_query_proto_rawDescGZIP() []byte {
	file_proto_cosmos_lms_v1beta1_query_proto_rawDescOnce.Do(func() {
		file_proto_cosmos_lms_v1beta1_query_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_cosmos_lms_v1beta1_query_proto_rawDescData)
	})
	return file_proto_cosmos_lms_v1beta1_query_proto_rawDescData
}

var file_proto_cosmos_lms_v1beta1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_cosmos_lms_v1beta1_query_proto_goTypes = []interface{}{
	(*GetStudentRequest)(nil),        // 0: lms.v1beta1.GetStudentRequest
	(*GetStudentResponse)(nil),       // 1: lms.v1beta1.GetStudentResponse
	(*GetStudentsRequest)(nil),       // 2: lms.v1beta1.GetStudentsRequest
	(*GetStudentsResponse)(nil),      // 3: lms.v1beta1.GetStudentsResponse
	(*GetLeaveRequestsRequest)(nil),  // 4: lms.v1beta1.GetLeaveRequestsRequest
	(*GetLeaveRequestsResponse)(nil), // 5: lms.v1beta1.GetLeaveRequestsResponse
	(*GetLeaveApprovesRequest)(nil),  // 6: lms.v1beta1.GetLeaveApprovesRequest
	(*GetLeaveApprovesResponse)(nil), // 7: lms.v1beta1.GetLeaveApprovesResponse
	(*Student)(nil),                  // 8: lms.v1beta1.Student
	(*ApplyLeaveRequest)(nil),        // 9: lms.v1beta1.ApplyLeaveRequest
	(*AcceptLeaveRequest)(nil),       // 10: lms.v1beta1.AcceptLeaveRequest
}
var file_proto_cosmos_lms_v1beta1_query_proto_depIdxs = []int32{
	8,  // 0: lms.v1beta1.GetStudentResponse.student:type_name -> lms.v1beta1.Student
	8,  // 1: lms.v1beta1.GetStudentsResponse.students:type_name -> lms.v1beta1.Student
	9,  // 2: lms.v1beta1.GetLeaveRequestsResponse.leaverequest:type_name -> lms.v1beta1.ApplyLeaveRequest
	10, // 3: lms.v1beta1.GetLeaveApprovesResponse.leaveapprove:type_name -> lms.v1beta1.AcceptLeaveRequest
	2,  // 4: lms.v1beta1.Query.GetStudents:input_type -> lms.v1beta1.GetStudentsRequest
	0,  // 5: lms.v1beta1.Query.GetStudent:input_type -> lms.v1beta1.GetStudentRequest
	4,  // 6: lms.v1beta1.Query.GetLeaveRequests:input_type -> lms.v1beta1.GetLeaveRequestsRequest
	6,  // 7: lms.v1beta1.Query.GetLeaveApproves:input_type -> lms.v1beta1.GetLeaveApprovesRequest
	3,  // 8: lms.v1beta1.Query.GetStudents:output_type -> lms.v1beta1.GetStudentsResponse
	1,  // 9: lms.v1beta1.Query.GetStudent:output_type -> lms.v1beta1.GetStudentResponse
	7,  // 10: lms.v1beta1.Query.GetLeaveRequests:output_type -> lms.v1beta1.GetLeaveApprovesResponse
	7,  // 11: lms.v1beta1.Query.GetLeaveApproves:output_type -> lms.v1beta1.GetLeaveApprovesResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_cosmos_lms_v1beta1_query_proto_init() }
func file_proto_cosmos_lms_v1beta1_query_proto_init() {
	if File_proto_cosmos_lms_v1beta1_query_proto != nil {
		return
	}
	file_proto_cosmos_lms_v1beta1_tx_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_cosmos_lms_v1beta1_query_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStudentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_cosmos_lms_v1beta1_query_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStudentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_cosmos_lms_v1beta1_query_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStudentsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_cosmos_lms_v1beta1_query_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStudentsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_cosmos_lms_v1beta1_query_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLeaveRequestsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_cosmos_lms_v1beta1_query_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLeaveRequestsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_cosmos_lms_v1beta1_query_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLeaveApprovesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_cosmos_lms_v1beta1_query_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLeaveApprovesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_cosmos_lms_v1beta1_query_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_cosmos_lms_v1beta1_query_proto_goTypes,
		DependencyIndexes: file_proto_cosmos_lms_v1beta1_query_proto_depIdxs,
		MessageInfos:      file_proto_cosmos_lms_v1beta1_query_proto_msgTypes,
	}.Build()
	File_proto_cosmos_lms_v1beta1_query_proto = out.File
	file_proto_cosmos_lms_v1beta1_query_proto_rawDesc = nil
	file_proto_cosmos_lms_v1beta1_query_proto_goTypes = nil
	file_proto_cosmos_lms_v1beta1_query_proto_depIdxs = nil
}
